export const GLOBAL_SET_CHAT_STAGE = "GLOBAL_SET_CHAT_STAGE";

export const MESSAGE_APPEND = "MESSAGE_APPEND";
export const MESSAGE_REMOVE = "MESSAGE_REMOVE";

export const USER_ADD_FIELDS = "USER_ADD_FIELDS";
