export const WAITING_FOR_BOT = "WAITING_FOR_BOT";
export const WAITING_FOR_FULL_NAME = "WAITING_FOR_FULL_NAME";
export const WAITING_FOR_CNPJ = "WAITING_FOR_CNPJ";
export const WAITING_FOR_ANSWER_1 = "WAITING_FOR_ANSWER_1";
export const WAITING_FOR_ANSWER_2 = "WAITING_FOR_ANSWER_2";
export const WAITING_FOR_ANSWER_3 = "WAITING_FOR_ANSWER_3";
export const WAITING_FOR_ANSWER_4 = "WAITING_FOR_ANSWER_4";
export const WAITING_FOR_ANSWER_5 = "WAITING_FOR_ANSWER_5";
export const WAITING_FOR_ANSWER_6 = "WAITING_FOR_ANSWER_6";
export const WAITING_FOR_ANSWER_7 = "WAITING_FOR_ANSWER_7";
export const WAITING_FOR_CNPJ_FETCHING = "WAITING_FOR_CNPJ_FETCHING";
export const WAITING_FOR_BUSINESS_TYPE = "WAITING_FOR_BUSINESS_TYPE";
export const WAITING_FOR_QUESTIONS_START = "WAITING_FOR_QUESTIONS_START";

export default {
  WAITING_FOR_BOT,
  WAITING_FOR_CNPJ,
  WAITING_FOR_FULL_NAME,
  WAITING_FOR_ANSWER_1,
  WAITING_FOR_ANSWER_2,
  WAITING_FOR_ANSWER_3,
  WAITING_FOR_ANSWER_4,
  WAITING_FOR_ANSWER_5,
  WAITING_FOR_ANSWER_6,
  WAITING_FOR_ANSWER_7,
  WAITING_FOR_CNPJ_FETCHING,
  WAITING_FOR_BUSINESS_TYPE,
  WAITING_FOR_QUESTIONS_START,
};
