export const WAITING_FOR_BOT = "WAITING_FOR_BOT";
export const WAITING_FOR_FULL_NAME = "WAITING_FOR_FULL_NAME";
export const WAITING_FOR_CNPJ = "WAITING_FOR_CNPJ";
export const WAITING_FOR_PHONE_NUMBER = "WAITING_FOR_PHONE_NUMBER";
export const WAITING_FOR_EMAIL = "WAITING_FOR_EMAIL";

export default {
  WAITING_FOR_BOT,
  WAITING_FOR_CNPJ,
  WAITING_FOR_FULL_NAME,
  WAITING_FOR_PHONE_NUMBER,
  WAITING_FOR_EMAIL,
};
